# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 13:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0002_auto_20161030_1919'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answers',
            new_name='Answer',
        ),
    ]
