# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0002_auto_20161026_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='course',
            field=models.ManyToManyField(blank=True, null=True, to='feeder.Course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ManyToManyField(blank=True, null=True, to='feeder.Course'),
        ),
    ]
