# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0003_auto_20161030_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assignment_name',
            field=models.CharField(max_length=50, verbose_name='Exam/Assignment'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='fb_name',
            field=models.CharField(max_length=100, verbose_name='Feedback Name'),
        ),
    ]
