# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0004_auto_20161031_0400'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.CharField(choices=[('SP', 'Spring'), ('AU', 'Autumn'), ('SU', 'Summer')], default='AU', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='roll_no',
            field=models.PositiveIntegerField(default=150050000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
