# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 20:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0006_auto_20161102_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responses1', models.PositiveIntegerField()),
                ('responses2', models.PositiveIntegerField()),
                ('responses3', models.PositiveIntegerField()),
                ('responses4', models.PositiveIntegerField()),
                ('responses5', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('rate', 'Rating Response'), ('text', 'Text Response')], default='text', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ratinganswer',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='feeder.Question'),
        ),
    ]
