# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0005_auto_20161102_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.CharField(max_length=11),
        ),
    ]
